### ISSUE TITLE
Plugin still not working with TShock v4.5.3

### ISSUE THREAD

**Issue by dringdahl** [Rozen4334/MapTP#2]
It seems there are bigger differences between v4.5.2 and v4.5.3 than you thought. I get a little blue ping when I click on the map, but I do not teleport (this was true in the prior version as well).

If it matters, the map I'm testing on is a journey celebration world.

Also, the plugin version still reports as v1.0.0.0 when it loads in TShock.

**Comment by Rozen4334** [comment]
As with this plugin, the same applies as with buildmode. Assembly is by nature 1.0, and the plugin has been extensively tested and working on 2 versions before latest and latest itself.

**Comment by dringdahl** [comment]
I don't really get what the difference between the release v1.2 and assembly v1.0 is, but it seems silly to report v1.0 between different releases when loading it into TShock as it makes it completely pointless to even report a version.

You're insisting the plugin works, but I've followed all instructions I've been given, and it still is not working for me. I'm happy to try other things if you have other suggestions, but I wouldn't know what would help.

**Comment by dringdahl** [comment]
OK, I don't know where it came from, but there was an extra TShockAPI.dll in the folder. I went through it file by file looking for anything that would explain why I might be having issues when you tested good and so I found that file that was not in the .zip. I removed it and the plugins appear to work now. I apologize for the trouble. Seems the problem was on my end.
